weather:
  uri: http://wthrcdn.etouch.cn/weather_mini?
spring:
  application:
    name: msa-weather-data-server

eureka:
    # 服务的url
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9993
